project:
  type: website
  output-dir: docs

website:
  title: "Anything"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources and Things
      - href: memepage.qmd
        text: Memes

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



